#!/usr/bin/env bash
set -euo pipefail

# Regenerate Go clients from Anchor IDLs using go-anchor.
# Usage:
#   ./scripts/generate-anchor-clients.sh [IDL_DIR]
# Example:
#   ./scripts/generate-anchor-clients.sh ../easyclaw-contract/target/idl

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [[ $# -ge 1 ]]; then
  IDL_DIR="$1"
else
  if [[ -d "${BACKEND_DIR}/../easyclaw-contract/target/idl" ]]; then
    IDL_DIR="${BACKEND_DIR}/../easyclaw-contract/target/idl"
  elif [[ -d "${BACKEND_DIR}/../easyclaw-contract/idl" ]]; then
    IDL_DIR="${BACKEND_DIR}/../easyclaw-contract/idl"
  else
    IDL_DIR="${BACKEND_DIR}/../contract/idl"
  fi
fi

if [[ ! -d "${IDL_DIR}" ]]; then
  echo "IDL directory not found: ${IDL_DIR}" >&2
  exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

PROGRAM_ID_ORDER_ENGINE="${ORDER_ENGINE_PROGRAM_ID:-GpMobZUKPtEE1eiZQAADo2ecD54JXhNHPNts5kPGwLtb}"
PROGRAM_ID_LP_VAULT="${LP_VAULT_PROGRAM_ID:-F8gkLV5nMaCG16PQAwkKKsTdWC2yuPektUXAFHQF4Cds}"

generate_program() {
  local idl_name="$1"
  local output_pkg_dir="$2"
  local program_id="$3"

  local gen_dir="${TMP_DIR}/${idl_name}"
  mkdir -p "${gen_dir}"

  go run github.com/gagliardetto/anchor-go@v1.0.0 \
    --idl "${IDL_DIR}/${idl_name}.json" \
    --output "${gen_dir}" \
    --program-id "${program_id}"

  mkdir -p "${output_pkg_dir}"
  cp "${gen_dir}/accounts.go" "${output_pkg_dir}/"
  cp "${gen_dir}/constants.go" "${output_pkg_dir}/"
  cp "${gen_dir}/discriminators.go" "${output_pkg_dir}/"
  cp "${gen_dir}/doc.go" "${output_pkg_dir}/"
  cp "${gen_dir}/errors.go" "${output_pkg_dir}/"
  cp "${gen_dir}/fetchers.go" "${output_pkg_dir}/"
  cp "${gen_dir}/instructions.go" "${output_pkg_dir}/"
  cp "${gen_dir}/program-id.go" "${output_pkg_dir}/"
  cp "${gen_dir}/types.go" "${output_pkg_dir}/"

  cat > "${output_pkg_dir}/program-id.go" <<EOF
// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package ${idl_name}

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("${program_id}")
EOF
}

generate_program "order_engine" "${BACKEND_DIR}/internal/anchor/order_engine" "${PROGRAM_ID_ORDER_ENGINE}"
generate_program "lp_vault" "${BACKEND_DIR}/internal/anchor/lp_vault" "${PROGRAM_ID_LP_VAULT}"

echo "go-anchor client generation completed."
