// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package order_engine

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_EngineConfig:
		value := new(EngineConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as EngineConfig: %w", err)
		}
		return value, nil
	case Account_GlobalConfig:
		value := new(GlobalConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as GlobalConfig: %w", err)
		}
		return value, nil
	case Account_KeeperRebate:
		value := new(KeeperRebate)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as KeeperRebate: %w", err)
		}
		return value, nil
	case Account_KeeperSet:
		value := new(KeeperSet)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as KeeperSet: %w", err)
		}
		return value, nil
	case Account_Market:
		value := new(Market)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Market: %w", err)
		}
		return value, nil
	case Account_MarketFundingState:
		value := new(MarketFundingState)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as MarketFundingState: %w", err)
		}
		return value, nil
	case Account_Order:
		value := new(Order)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Order: %w", err)
		}
		return value, nil
	case Account_Pool:
		value := new(Pool)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Pool: %w", err)
		}
		return value, nil
	case Account_UserMargin:
		value := new(UserMargin)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as UserMargin: %w", err)
		}
		return value, nil
	case Account_UserMarketPosition:
		value := new(UserMarketPosition)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as UserMarketPosition: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_EngineConfig(accountData []byte) (*EngineConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_EngineConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_EngineConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(EngineConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type EngineConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_GlobalConfig(accountData []byte) (*GlobalConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_GlobalConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_GlobalConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(GlobalConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type GlobalConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_KeeperRebate(accountData []byte) (*KeeperRebate, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_KeeperRebate {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_KeeperRebate, binary.FormatDiscriminator(discriminator))
	}
	acc := new(KeeperRebate)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type KeeperRebate: %w", err)
	}
	return acc, nil
}

func ParseAccount_KeeperSet(accountData []byte) (*KeeperSet, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_KeeperSet {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_KeeperSet, binary.FormatDiscriminator(discriminator))
	}
	acc := new(KeeperSet)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type KeeperSet: %w", err)
	}
	return acc, nil
}

func ParseAccount_Market(accountData []byte) (*Market, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Market {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Market, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Market)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Market: %w", err)
	}
	return acc, nil
}

func ParseAccount_MarketFundingState(accountData []byte) (*MarketFundingState, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_MarketFundingState {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_MarketFundingState, binary.FormatDiscriminator(discriminator))
	}
	acc := new(MarketFundingState)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type MarketFundingState: %w", err)
	}
	return acc, nil
}

func ParseAccount_Order(accountData []byte) (*Order, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Order {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Order, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Order)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Order: %w", err)
	}
	return acc, nil
}

func ParseAccount_Pool(accountData []byte) (*Pool, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Pool {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Pool, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Pool)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Pool: %w", err)
	}
	return acc, nil
}

func ParseAccount_UserMargin(accountData []byte) (*UserMargin, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_UserMargin {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_UserMargin, binary.FormatDiscriminator(discriminator))
	}
	acc := new(UserMargin)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type UserMargin: %w", err)
	}
	return acc, nil
}

func ParseAccount_UserMarketPosition(accountData []byte) (*UserMarketPosition, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_UserMarketPosition {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_UserMarketPosition, binary.FormatDiscriminator(discriminator))
	}
	acc := new(UserMarketPosition)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type UserMarketPosition: %w", err)
	}
	return acc, nil
}
