// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package order_engine

// Account discriminators
var (
	Account_EngineConfig       = [8]byte{10, 197, 172, 236, 51, 169, 22, 207}
	Account_GlobalConfig       = [8]byte{149, 8, 156, 202, 160, 252, 176, 217}
	Account_KeeperRebate       = [8]byte{132, 91, 111, 117, 222, 69, 126, 108}
	Account_KeeperSet          = [8]byte{128, 74, 91, 225, 246, 113, 55, 177}
	Account_Market             = [8]byte{219, 190, 213, 55, 0, 227, 198, 154}
	Account_MarketFundingState = [8]byte{225, 216, 170, 48, 11, 238, 62, 71}
	Account_Order              = [8]byte{134, 173, 223, 185, 77, 86, 28, 51}
	Account_Pool               = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	Account_UserMargin         = [8]byte{198, 202, 205, 196, 42, 177, 76, 75}
	Account_UserMarketPosition = [8]byte{173, 173, 210, 19, 141, 85, 211, 21}
)

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_CancelOrder                  = [8]byte{95, 129, 237, 240, 8, 49, 223, 132}
	Instruction_CancelOrderByExecutor        = [8]byte{124, 156, 17, 87, 230, 139, 57, 158}
	Instruction_CreateMarginAccount          = [8]byte{98, 114, 213, 184, 129, 89, 90, 185}
	Instruction_CreateUserMarketPosition     = [8]byte{184, 183, 182, 125, 240, 234, 69, 166}
	Instruction_DepositCollateral            = [8]byte{156, 131, 142, 116, 146, 247, 162, 120}
	Instruction_ExecuteOrder                 = [8]byte{115, 61, 180, 24, 168, 32, 215, 20}
	Instruction_InitializeEngine             = [8]byte{17, 158, 153, 215, 119, 242, 156, 107}
	Instruction_InitializeMarketFundingState = [8]byte{35, 52, 158, 172, 35, 170, 27, 169}
	Instruction_Liquidate                    = [8]byte{223, 179, 226, 125, 48, 46, 39, 74}
	Instruction_PlaceOrder                   = [8]byte{51, 194, 155, 175, 109, 130, 96, 106}
	Instruction_WithdrawCollateral           = [8]byte{115, 135, 168, 106, 139, 214, 138, 150}
)
