// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package order_engine

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "cancel_order" instruction.
func NewCancelOrderInstruction(
	userAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	orderAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, false, true))
		// Account 1 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 2 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 3 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 4 "order": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "cancel_order_by_executor" instruction.
func NewCancelOrderByExecutorInstruction(
	executorAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	keeperSetAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	orderAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "executor": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(executorAccount, false, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 3 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 4 "keeper_set": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperSetAccount, false, false))
		// Account 5 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 6 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 7 "order": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_margin_account" instruction.
func NewCreateMarginAccountInstruction(
	userAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "create_user_market_position" instruction.
func NewCreateUserMarketPositionInstruction(
	// Params:
	marketIdParam uint64,

	// Accounts:
	userAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	userMarketPositionAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_CreateUserMarketPosition[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 3 "user_market_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarketPositionAccount, true, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "deposit_collateral" instruction.
func NewDepositCollateralInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	userAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	collateralVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_DepositCollateral[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 3 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 4 "collateral_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(collateralVaultAccount, true, false))
		// Account 5 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "execute_order" instruction.
func NewExecuteOrderInstruction(
	// Params:
	fillPriceParam uint64,
	oraclePriceParam uint64,
	oracleConfParam uint64,
	oraclePublishTimeParam int64,

	// Accounts:
	executorAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	keeperSetAccount solanago.PublicKey,
	orderAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	oraclePriceUpdateAccount solanago.PublicKey,
	marketFundingStateAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	userMarketPositionAccount solanago.PublicKey,
	engineAuthorityAccount solanago.PublicKey,
	collateralVaultAccount solanago.PublicKey,
	lpVaultProgramAccount solanago.PublicKey,
	lpPoolAccount solanago.PublicKey,
	lpLiquidityVaultAccount solanago.PublicKey,
	lpInsuranceVaultAccount solanago.PublicKey,
	lpProtocolFeeVaultAccount solanago.PublicKey,
	keeperRebateAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ExecuteOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `fillPriceParam`:
		err = enc__.Encode(fillPriceParam)
		if err != nil {
			return nil, errors.NewField("fillPriceParam", err)
		}
		// Serialize `oraclePriceParam`:
		err = enc__.Encode(oraclePriceParam)
		if err != nil {
			return nil, errors.NewField("oraclePriceParam", err)
		}
		// Serialize `oracleConfParam`:
		err = enc__.Encode(oracleConfParam)
		if err != nil {
			return nil, errors.NewField("oracleConfParam", err)
		}
		// Serialize `oraclePublishTimeParam`:
		err = enc__.Encode(oraclePublishTimeParam)
		if err != nil {
			return nil, errors.NewField("oraclePublishTimeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "executor": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(executorAccount, false, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 3 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 4 "keeper_set": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperSetAccount, false, false))
		// Account 5 "order": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
		// Account 6 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 7 "oracle_price_update": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(oraclePriceUpdateAccount, false, false))
		// Account 8 "market_funding_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketFundingStateAccount, true, false))
		// Account 9 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 10 "user_market_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarketPositionAccount, true, false))
		// Account 11 "engine_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, false))
		// Account 12 "collateral_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(collateralVaultAccount, true, false))
		// Account 13 "lp_vault_program": Read-only, Non-signer, Required, Address: 7A7BCZChVprUa3WBbC7mER54E7BVGA7PussRB8fHC5tz
		accounts__.Append(solanago.NewAccountMeta(lpVaultProgramAccount, false, false))
		// Account 14 "lp_pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPoolAccount, true, false))
		// Account 15 "lp_liquidity_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpLiquidityVaultAccount, true, false))
		// Account 16 "lp_insurance_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpInsuranceVaultAccount, true, false))
		// Account 17 "lp_protocol_fee_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpProtocolFeeVaultAccount, true, false))
		// Account 18 "keeper_rebate": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperRebateAccount, true, false))
		// Account 19 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "initialize_engine" instruction.
func NewInitializeEngineInstruction(
	// Params:
	maxTtlSecsParam int64,
	liquidationPenaltyBpsParam uint16,
	maxImrBpsParam uint16,

	// Accounts:
	adminAccount solanago.PublicKey,
	usdcMintAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	keeperSetAccount solanago.PublicKey,
	lpVaultProgramAccount solanago.PublicKey,
	lpPoolAccount solanago.PublicKey,
	lpLiquidityVaultAccount solanago.PublicKey,
	lpInsuranceVaultAccount solanago.PublicKey,
	lpProtocolFeeVaultAccount solanago.PublicKey,
	engineAuthorityAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	collateralVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_InitializeEngine[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `maxTtlSecsParam`:
		err = enc__.Encode(maxTtlSecsParam)
		if err != nil {
			return nil, errors.NewField("maxTtlSecsParam", err)
		}
		// Serialize `liquidationPenaltyBpsParam`:
		err = enc__.Encode(liquidationPenaltyBpsParam)
		if err != nil {
			return nil, errors.NewField("liquidationPenaltyBpsParam", err)
		}
		// Serialize `maxImrBpsParam`:
		err = enc__.Encode(maxImrBpsParam)
		if err != nil {
			return nil, errors.NewField("maxImrBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, true, true))
		// Account 1 "usdc_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(usdcMintAccount, false, false))
		// Account 2 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 3 "global_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, true, false))
		// Account 4 "keeper_set": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperSetAccount, false, false))
		// Account 5 "lp_vault_program": Read-only, Non-signer, Required, Address: 7A7BCZChVprUa3WBbC7mER54E7BVGA7PussRB8fHC5tz
		accounts__.Append(solanago.NewAccountMeta(lpVaultProgramAccount, false, false))
		// Account 6 "lp_pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPoolAccount, false, false))
		// Account 7 "lp_liquidity_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpLiquidityVaultAccount, false, false))
		// Account 8 "lp_insurance_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpInsuranceVaultAccount, false, false))
		// Account 9 "lp_protocol_fee_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpProtocolFeeVaultAccount, false, false))
		// Account 10 "engine_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, false))
		// Account 11 "engine_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, true, false))
		// Account 12 "collateral_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(collateralVaultAccount, true, false))
		// Account 13 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 14 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "initialize_market_funding_state" instruction.
func NewInitializeMarketFundingStateInstruction(
	// Params:
	marketIdParam uint64,

	// Accounts:
	adminAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketFundingStateAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_InitializeMarketFundingState[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, true, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 3 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 4 "market_funding_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketFundingStateAccount, true, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "liquidate" instruction.
func NewLiquidateInstruction(
	// Params:
	marketIdParam uint64,
	legParam PositionLeg,
	closeQtyParam uint64,

	// Accounts:
	executorAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	keeperSetAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	marketFundingStateAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	userMarketPositionAccount solanago.PublicKey,
	engineAuthorityAccount solanago.PublicKey,
	collateralVaultAccount solanago.PublicKey,
	lpVaultProgramAccount solanago.PublicKey,
	lpPoolAccount solanago.PublicKey,
	lpInsuranceVaultAccount solanago.PublicKey,
	lpProtocolFeeVaultAccount solanago.PublicKey,
	keeperRebateAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Liquidate[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
		// Serialize `legParam`:
		err = enc__.Encode(legParam)
		if err != nil {
			return nil, errors.NewField("legParam", err)
		}
		// Serialize `closeQtyParam`:
		err = enc__.Encode(closeQtyParam)
		if err != nil {
			return nil, errors.NewField("closeQtyParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "executor": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(executorAccount, false, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 3 "keeper_set": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperSetAccount, false, false))
		// Account 4 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 5 "market_funding_state": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketFundingStateAccount, true, false))
		// Account 6 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 7 "user_market_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarketPositionAccount, true, false))
		// Account 8 "engine_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, false))
		// Account 9 "collateral_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(collateralVaultAccount, true, false))
		// Account 10 "lp_vault_program": Read-only, Non-signer, Required, Address: 7A7BCZChVprUa3WBbC7mER54E7BVGA7PussRB8fHC5tz
		accounts__.Append(solanago.NewAccountMeta(lpVaultProgramAccount, false, false))
		// Account 11 "lp_pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPoolAccount, true, false))
		// Account 12 "lp_insurance_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpInsuranceVaultAccount, true, false))
		// Account 13 "lp_protocol_fee_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpProtocolFeeVaultAccount, true, false))
		// Account 14 "keeper_rebate": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperRebateAccount, true, false))
		// Account 15 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "place_order" instruction.
func NewPlaceOrderInstruction(
	// Params:
	marketIdParam uint64,
	sideParam Side,
	orderTypeParam OrderType,
	reduceOnlyParam bool,
	marginParam uint64,
	priceParam uint64,
	ttlSecsParam int64,
	clientOrderIdParam uint64,

	// Accounts:
	userAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	marketRegistryProgramAccount solanago.PublicKey,
	globalConfigAccount solanago.PublicKey,
	marketAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	orderAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_PlaceOrder[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
		// Serialize `sideParam`:
		err = enc__.Encode(sideParam)
		if err != nil {
			return nil, errors.NewField("sideParam", err)
		}
		// Serialize `orderTypeParam`:
		err = enc__.Encode(orderTypeParam)
		if err != nil {
			return nil, errors.NewField("orderTypeParam", err)
		}
		// Serialize `reduceOnlyParam`:
		err = enc__.Encode(reduceOnlyParam)
		if err != nil {
			return nil, errors.NewField("reduceOnlyParam", err)
		}
		// Serialize `marginParam`:
		err = enc__.Encode(marginParam)
		if err != nil {
			return nil, errors.NewField("marginParam", err)
		}
		// Serialize `priceParam`:
		err = enc__.Encode(priceParam)
		if err != nil {
			return nil, errors.NewField("priceParam", err)
		}
		// Serialize `ttlSecsParam`:
		err = enc__.Encode(ttlSecsParam)
		if err != nil {
			return nil, errors.NewField("ttlSecsParam", err)
		}
		// Serialize `clientOrderIdParam`:
		err = enc__.Encode(clientOrderIdParam)
		if err != nil {
			return nil, errors.NewField("clientOrderIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "market_registry_program": Read-only, Non-signer, Required, Address: Gswa2NzGEuUeM5MekCTJ9rLyzsocW1FENHue5f3uiDr7
		accounts__.Append(solanago.NewAccountMeta(marketRegistryProgramAccount, false, false))
		// Account 3 "global_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(globalConfigAccount, false, false))
		// Account 4 "market": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(marketAccount, false, false))
		// Account 5 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 6 "order": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderAccount, true, false))
		// Account 7 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "withdraw_collateral" instruction.
func NewWithdrawCollateralInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	userAccount solanago.PublicKey,
	engineConfigAccount solanago.PublicKey,
	userMarginAccount solanago.PublicKey,
	engineAuthorityAccount solanago.PublicKey,
	collateralVaultAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_WithdrawCollateral[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "engine_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineConfigAccount, false, false))
		// Account 2 "user_margin": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userMarginAccount, true, false))
		// Account 3 "engine_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, false))
		// Account 4 "collateral_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(collateralVaultAccount, true, false))
		// Account 5 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 6 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
