// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package order_engine

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("7zpq5Xg74SEX1NchVzQXgG3JEFmHhnBJzFR9LXGuaBSj")
