// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package order_engine

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type EngineConfig struct {
	Admin                 solanago.PublicKey `json:"admin"`
	UsdcMint              solanago.PublicKey `json:"usdcMint"`
	CollateralVault       solanago.PublicKey `json:"collateralVault"`
	RegistryProgram       solanago.PublicKey `json:"registryProgram"`
	RegistryGlobalConfig  solanago.PublicKey `json:"registryGlobalConfig"`
	KeeperSet             solanago.PublicKey `json:"keeperSet"`
	LpVaultProgram        solanago.PublicKey `json:"lpVaultProgram"`
	LpPool                solanago.PublicKey `json:"lpPool"`
	LpLiquidityVault      solanago.PublicKey `json:"lpLiquidityVault"`
	LpInsuranceVault      solanago.PublicKey `json:"lpInsuranceVault"`
	LpProtocolFeeVault    solanago.PublicKey `json:"lpProtocolFeeVault"`
	EngineAuthority       solanago.PublicKey `json:"engineAuthority"`
	MaxTtlSecs            int64              `json:"maxTtlSecs"`
	LiquidationPenaltyBps uint16             `json:"liquidationPenaltyBps"`
	MaxImrBps             uint16             `json:"maxImrBps"`
	Bump                  uint8              `json:"bump"`
}

func (obj EngineConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `UsdcMint`:
	err = encoder.Encode(obj.UsdcMint)
	if err != nil {
		return errors.NewField("UsdcMint", err)
	}
	// Serialize `CollateralVault`:
	err = encoder.Encode(obj.CollateralVault)
	if err != nil {
		return errors.NewField("CollateralVault", err)
	}
	// Serialize `RegistryProgram`:
	err = encoder.Encode(obj.RegistryProgram)
	if err != nil {
		return errors.NewField("RegistryProgram", err)
	}
	// Serialize `RegistryGlobalConfig`:
	err = encoder.Encode(obj.RegistryGlobalConfig)
	if err != nil {
		return errors.NewField("RegistryGlobalConfig", err)
	}
	// Serialize `KeeperSet`:
	err = encoder.Encode(obj.KeeperSet)
	if err != nil {
		return errors.NewField("KeeperSet", err)
	}
	// Serialize `LpVaultProgram`:
	err = encoder.Encode(obj.LpVaultProgram)
	if err != nil {
		return errors.NewField("LpVaultProgram", err)
	}
	// Serialize `LpPool`:
	err = encoder.Encode(obj.LpPool)
	if err != nil {
		return errors.NewField("LpPool", err)
	}
	// Serialize `LpLiquidityVault`:
	err = encoder.Encode(obj.LpLiquidityVault)
	if err != nil {
		return errors.NewField("LpLiquidityVault", err)
	}
	// Serialize `LpInsuranceVault`:
	err = encoder.Encode(obj.LpInsuranceVault)
	if err != nil {
		return errors.NewField("LpInsuranceVault", err)
	}
	// Serialize `LpProtocolFeeVault`:
	err = encoder.Encode(obj.LpProtocolFeeVault)
	if err != nil {
		return errors.NewField("LpProtocolFeeVault", err)
	}
	// Serialize `EngineAuthority`:
	err = encoder.Encode(obj.EngineAuthority)
	if err != nil {
		return errors.NewField("EngineAuthority", err)
	}
	// Serialize `MaxTtlSecs`:
	err = encoder.Encode(obj.MaxTtlSecs)
	if err != nil {
		return errors.NewField("MaxTtlSecs", err)
	}
	// Serialize `LiquidationPenaltyBps`:
	err = encoder.Encode(obj.LiquidationPenaltyBps)
	if err != nil {
		return errors.NewField("LiquidationPenaltyBps", err)
	}
	// Serialize `MaxImrBps`:
	err = encoder.Encode(obj.MaxImrBps)
	if err != nil {
		return errors.NewField("MaxImrBps", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj EngineConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EngineConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EngineConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `UsdcMint`:
	err = decoder.Decode(&obj.UsdcMint)
	if err != nil {
		return errors.NewField("UsdcMint", err)
	}
	// Deserialize `CollateralVault`:
	err = decoder.Decode(&obj.CollateralVault)
	if err != nil {
		return errors.NewField("CollateralVault", err)
	}
	// Deserialize `RegistryProgram`:
	err = decoder.Decode(&obj.RegistryProgram)
	if err != nil {
		return errors.NewField("RegistryProgram", err)
	}
	// Deserialize `RegistryGlobalConfig`:
	err = decoder.Decode(&obj.RegistryGlobalConfig)
	if err != nil {
		return errors.NewField("RegistryGlobalConfig", err)
	}
	// Deserialize `KeeperSet`:
	err = decoder.Decode(&obj.KeeperSet)
	if err != nil {
		return errors.NewField("KeeperSet", err)
	}
	// Deserialize `LpVaultProgram`:
	err = decoder.Decode(&obj.LpVaultProgram)
	if err != nil {
		return errors.NewField("LpVaultProgram", err)
	}
	// Deserialize `LpPool`:
	err = decoder.Decode(&obj.LpPool)
	if err != nil {
		return errors.NewField("LpPool", err)
	}
	// Deserialize `LpLiquidityVault`:
	err = decoder.Decode(&obj.LpLiquidityVault)
	if err != nil {
		return errors.NewField("LpLiquidityVault", err)
	}
	// Deserialize `LpInsuranceVault`:
	err = decoder.Decode(&obj.LpInsuranceVault)
	if err != nil {
		return errors.NewField("LpInsuranceVault", err)
	}
	// Deserialize `LpProtocolFeeVault`:
	err = decoder.Decode(&obj.LpProtocolFeeVault)
	if err != nil {
		return errors.NewField("LpProtocolFeeVault", err)
	}
	// Deserialize `EngineAuthority`:
	err = decoder.Decode(&obj.EngineAuthority)
	if err != nil {
		return errors.NewField("EngineAuthority", err)
	}
	// Deserialize `MaxTtlSecs`:
	err = decoder.Decode(&obj.MaxTtlSecs)
	if err != nil {
		return errors.NewField("MaxTtlSecs", err)
	}
	// Deserialize `LiquidationPenaltyBps`:
	err = decoder.Decode(&obj.LiquidationPenaltyBps)
	if err != nil {
		return errors.NewField("LiquidationPenaltyBps", err)
	}
	// Deserialize `MaxImrBps`:
	err = decoder.Decode(&obj.MaxImrBps)
	if err != nil {
		return errors.NewField("MaxImrBps", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *EngineConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EngineConfig: %w", err)
	}
	return nil
}

func UnmarshalEngineConfig(buf []byte) (*EngineConfig, error) {
	obj := new(EngineConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type FeeParams struct {
	TakerFeeBps uint16 `json:"takerFeeBps"`
	MakerFeeBps uint16 `json:"makerFeeBps"`
}

func (obj FeeParams) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TakerFeeBps`:
	err = encoder.Encode(obj.TakerFeeBps)
	if err != nil {
		return errors.NewField("TakerFeeBps", err)
	}
	// Serialize `MakerFeeBps`:
	err = encoder.Encode(obj.MakerFeeBps)
	if err != nil {
		return errors.NewField("MakerFeeBps", err)
	}
	return nil
}

func (obj FeeParams) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeParams: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeParams) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TakerFeeBps`:
	err = decoder.Decode(&obj.TakerFeeBps)
	if err != nil {
		return errors.NewField("TakerFeeBps", err)
	}
	// Deserialize `MakerFeeBps`:
	err = decoder.Decode(&obj.MakerFeeBps)
	if err != nil {
		return errors.NewField("MakerFeeBps", err)
	}
	return nil
}

func (obj *FeeParams) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeParams: %w", err)
	}
	return nil
}

func UnmarshalFeeParams(buf []byte) (*FeeParams, error) {
	obj := new(FeeParams)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type FeeSplit struct {
	LpBps        uint16 `json:"lpBps"`
	InsuranceBps uint16 `json:"insuranceBps"`
	ProtocolBps  uint16 `json:"protocolBps"`
}

func (obj FeeSplit) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `LpBps`:
	err = encoder.Encode(obj.LpBps)
	if err != nil {
		return errors.NewField("LpBps", err)
	}
	// Serialize `InsuranceBps`:
	err = encoder.Encode(obj.InsuranceBps)
	if err != nil {
		return errors.NewField("InsuranceBps", err)
	}
	// Serialize `ProtocolBps`:
	err = encoder.Encode(obj.ProtocolBps)
	if err != nil {
		return errors.NewField("ProtocolBps", err)
	}
	return nil
}

func (obj FeeSplit) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeSplit: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeSplit) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `LpBps`:
	err = decoder.Decode(&obj.LpBps)
	if err != nil {
		return errors.NewField("LpBps", err)
	}
	// Deserialize `InsuranceBps`:
	err = decoder.Decode(&obj.InsuranceBps)
	if err != nil {
		return errors.NewField("InsuranceBps", err)
	}
	// Deserialize `ProtocolBps`:
	err = decoder.Decode(&obj.ProtocolBps)
	if err != nil {
		return errors.NewField("ProtocolBps", err)
	}
	return nil
}

func (obj *FeeSplit) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeSplit: %w", err)
	}
	return nil
}

func UnmarshalFeeSplit(buf []byte) (*FeeSplit, error) {
	obj := new(FeeSplit)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type FundingParams struct {
	IntervalSec                 int64 `json:"intervalSec"`
	FundingVelocityCapBpsPerDay int64 `json:"fundingVelocityCapBpsPerDay"`
	PremiumClampBps             int64 `json:"premiumClampBps"`
}

func (obj FundingParams) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `IntervalSec`:
	err = encoder.Encode(obj.IntervalSec)
	if err != nil {
		return errors.NewField("IntervalSec", err)
	}
	// Serialize `FundingVelocityCapBpsPerDay`:
	err = encoder.Encode(obj.FundingVelocityCapBpsPerDay)
	if err != nil {
		return errors.NewField("FundingVelocityCapBpsPerDay", err)
	}
	// Serialize `PremiumClampBps`:
	err = encoder.Encode(obj.PremiumClampBps)
	if err != nil {
		return errors.NewField("PremiumClampBps", err)
	}
	return nil
}

func (obj FundingParams) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FundingParams: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FundingParams) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `IntervalSec`:
	err = decoder.Decode(&obj.IntervalSec)
	if err != nil {
		return errors.NewField("IntervalSec", err)
	}
	// Deserialize `FundingVelocityCapBpsPerDay`:
	err = decoder.Decode(&obj.FundingVelocityCapBpsPerDay)
	if err != nil {
		return errors.NewField("FundingVelocityCapBpsPerDay", err)
	}
	// Deserialize `PremiumClampBps`:
	err = decoder.Decode(&obj.PremiumClampBps)
	if err != nil {
		return errors.NewField("PremiumClampBps", err)
	}
	return nil
}

func (obj *FundingParams) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FundingParams: %w", err)
	}
	return nil
}

func UnmarshalFundingParams(buf []byte) (*FundingParams, error) {
	obj := new(FundingParams)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type GlobalConfig struct {
	Multisig      solanago.PublicKey `json:"multisig"`
	GlobalPause   bool               `json:"globalPause"`
	FeeSplit      FeeSplit           `json:"feeSplit"`
	KeeperSet     solanago.PublicKey `json:"keeperSet"`
	CreatedAt     int64              `json:"createdAt"`
	LastUpdatedAt int64              `json:"lastUpdatedAt"`
	Bump          uint8              `json:"bump"`
}

func (obj GlobalConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Multisig`:
	err = encoder.Encode(obj.Multisig)
	if err != nil {
		return errors.NewField("Multisig", err)
	}
	// Serialize `GlobalPause`:
	err = encoder.Encode(obj.GlobalPause)
	if err != nil {
		return errors.NewField("GlobalPause", err)
	}
	// Serialize `FeeSplit`:
	err = encoder.Encode(obj.FeeSplit)
	if err != nil {
		return errors.NewField("FeeSplit", err)
	}
	// Serialize `KeeperSet`:
	err = encoder.Encode(obj.KeeperSet)
	if err != nil {
		return errors.NewField("KeeperSet", err)
	}
	// Serialize `CreatedAt`:
	err = encoder.Encode(obj.CreatedAt)
	if err != nil {
		return errors.NewField("CreatedAt", err)
	}
	// Serialize `LastUpdatedAt`:
	err = encoder.Encode(obj.LastUpdatedAt)
	if err != nil {
		return errors.NewField("LastUpdatedAt", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj GlobalConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding GlobalConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *GlobalConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Multisig`:
	err = decoder.Decode(&obj.Multisig)
	if err != nil {
		return errors.NewField("Multisig", err)
	}
	// Deserialize `GlobalPause`:
	err = decoder.Decode(&obj.GlobalPause)
	if err != nil {
		return errors.NewField("GlobalPause", err)
	}
	// Deserialize `FeeSplit`:
	err = decoder.Decode(&obj.FeeSplit)
	if err != nil {
		return errors.NewField("FeeSplit", err)
	}
	// Deserialize `KeeperSet`:
	err = decoder.Decode(&obj.KeeperSet)
	if err != nil {
		return errors.NewField("KeeperSet", err)
	}
	// Deserialize `CreatedAt`:
	err = decoder.Decode(&obj.CreatedAt)
	if err != nil {
		return errors.NewField("CreatedAt", err)
	}
	// Deserialize `LastUpdatedAt`:
	err = decoder.Decode(&obj.LastUpdatedAt)
	if err != nil {
		return errors.NewField("LastUpdatedAt", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *GlobalConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling GlobalConfig: %w", err)
	}
	return nil
}

func UnmarshalGlobalConfig(buf []byte) (*GlobalConfig, error) {
	obj := new(GlobalConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type KeeperRebate struct {
	Pool   solanago.PublicKey `json:"pool"`
	Keeper solanago.PublicKey `json:"keeper"`
	Amount uint64             `json:"amount"`
	Bump   uint8              `json:"bump"`
}

func (obj KeeperRebate) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `Keeper`:
	err = encoder.Encode(obj.Keeper)
	if err != nil {
		return errors.NewField("Keeper", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj KeeperRebate) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding KeeperRebate: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *KeeperRebate) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `Keeper`:
	err = decoder.Decode(&obj.Keeper)
	if err != nil {
		return errors.NewField("Keeper", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *KeeperRebate) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling KeeperRebate: %w", err)
	}
	return nil
}

func UnmarshalKeeperRebate(buf []byte) (*KeeperRebate, error) {
	obj := new(KeeperRebate)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type KeeperSet struct {
	Authority solanago.PublicKey   `json:"authority"`
	Keepers   []solanago.PublicKey `json:"keepers"`
	Bump      uint8                `json:"bump"`
}

func (obj KeeperSet) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Keepers`:
	err = encoder.Encode(obj.Keepers)
	if err != nil {
		return errors.NewField("Keepers", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj KeeperSet) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding KeeperSet: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *KeeperSet) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Keepers`:
	err = decoder.Decode(&obj.Keepers)
	if err != nil {
		return errors.NewField("Keepers", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *KeeperSet) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling KeeperSet: %w", err)
	}
	return nil
}

func UnmarshalKeeperSet(buf []byte) (*KeeperSet, error) {
	obj := new(KeeperSet)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Market struct {
	MarketId      uint64             `json:"marketId"`
	Symbol        [16]uint8          `json:"symbol"`
	PythFeed      solanago.PublicKey `json:"pythFeed"`
	Status        MarketStatus       `json:"status"`
	RiskParams    RiskParams         `json:"riskParams"`
	PricingParams PricingParams      `json:"pricingParams"`
	FundingParams FundingParams      `json:"fundingParams"`
	FeeParams     FeeParams          `json:"feeParams"`
	Bump          uint8              `json:"bump"`
}

func (obj Market) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MarketId`:
	err = encoder.Encode(obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Serialize `Symbol`:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	// Serialize `PythFeed`:
	err = encoder.Encode(obj.PythFeed)
	if err != nil {
		return errors.NewField("PythFeed", err)
	}
	// Serialize `Status`:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Serialize `RiskParams`:
	err = encoder.Encode(obj.RiskParams)
	if err != nil {
		return errors.NewField("RiskParams", err)
	}
	// Serialize `PricingParams`:
	err = encoder.Encode(obj.PricingParams)
	if err != nil {
		return errors.NewField("PricingParams", err)
	}
	// Serialize `FundingParams`:
	err = encoder.Encode(obj.FundingParams)
	if err != nil {
		return errors.NewField("FundingParams", err)
	}
	// Serialize `FeeParams`:
	err = encoder.Encode(obj.FeeParams)
	if err != nil {
		return errors.NewField("FeeParams", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj Market) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Market: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Market) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MarketId`:
	err = decoder.Decode(&obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	// Deserialize `PythFeed`:
	err = decoder.Decode(&obj.PythFeed)
	if err != nil {
		return errors.NewField("PythFeed", err)
	}
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Deserialize `RiskParams`:
	err = decoder.Decode(&obj.RiskParams)
	if err != nil {
		return errors.NewField("RiskParams", err)
	}
	// Deserialize `PricingParams`:
	err = decoder.Decode(&obj.PricingParams)
	if err != nil {
		return errors.NewField("PricingParams", err)
	}
	// Deserialize `FundingParams`:
	err = decoder.Decode(&obj.FundingParams)
	if err != nil {
		return errors.NewField("FundingParams", err)
	}
	// Deserialize `FeeParams`:
	err = decoder.Decode(&obj.FeeParams)
	if err != nil {
		return errors.NewField("FeeParams", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *Market) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Market: %w", err)
	}
	return nil
}

func UnmarshalMarket(buf []byte) (*Market, error) {
	obj := new(Market)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type MarketFundingState struct {
	MarketId     uint64        `json:"marketId"`
	FundingIndex binary.Int128 `json:"fundingIndex"`
	LastUpdateTs int64         `json:"lastUpdateTs"`
	OpenInterest uint64        `json:"openInterest"`
	Skew         binary.Int128 `json:"skew"`
	Halted       bool          `json:"halted"`
	Bump         uint8         `json:"bump"`
}

func (obj MarketFundingState) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MarketId`:
	err = encoder.Encode(obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Serialize `FundingIndex`:
	err = encoder.Encode(obj.FundingIndex)
	if err != nil {
		return errors.NewField("FundingIndex", err)
	}
	// Serialize `LastUpdateTs`:
	err = encoder.Encode(obj.LastUpdateTs)
	if err != nil {
		return errors.NewField("LastUpdateTs", err)
	}
	// Serialize `OpenInterest`:
	err = encoder.Encode(obj.OpenInterest)
	if err != nil {
		return errors.NewField("OpenInterest", err)
	}
	// Serialize `Skew`:
	err = encoder.Encode(obj.Skew)
	if err != nil {
		return errors.NewField("Skew", err)
	}
	// Serialize `Halted`:
	err = encoder.Encode(obj.Halted)
	if err != nil {
		return errors.NewField("Halted", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj MarketFundingState) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding MarketFundingState: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *MarketFundingState) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MarketId`:
	err = decoder.Decode(&obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Deserialize `FundingIndex`:
	err = decoder.Decode(&obj.FundingIndex)
	if err != nil {
		return errors.NewField("FundingIndex", err)
	}
	// Deserialize `LastUpdateTs`:
	err = decoder.Decode(&obj.LastUpdateTs)
	if err != nil {
		return errors.NewField("LastUpdateTs", err)
	}
	// Deserialize `OpenInterest`:
	err = decoder.Decode(&obj.OpenInterest)
	if err != nil {
		return errors.NewField("OpenInterest", err)
	}
	// Deserialize `Skew`:
	err = decoder.Decode(&obj.Skew)
	if err != nil {
		return errors.NewField("Skew", err)
	}
	// Deserialize `Halted`:
	err = decoder.Decode(&obj.Halted)
	if err != nil {
		return errors.NewField("Halted", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *MarketFundingState) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling MarketFundingState: %w", err)
	}
	return nil
}

func UnmarshalMarketFundingState(buf []byte) (*MarketFundingState, error) {
	obj := new(MarketFundingState)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type MarketStatus binary.BorshEnum

const (
	MarketStatus_Active MarketStatus = iota
	MarketStatus_Paused
	MarketStatus_Halted
)

func (value MarketStatus) String() string {
	switch value {
	case MarketStatus_Active:
		return "Active"
	case MarketStatus_Paused:
		return "Paused"
	case MarketStatus_Halted:
		return "Halted"
	default:
		return ""
	}
}

type Order struct {
	Id            uint64             `json:"id"`
	UserMargin    solanago.PublicKey `json:"userMargin"`
	User          solanago.PublicKey `json:"user"`
	MarketId      uint64             `json:"marketId"`
	Side          Side               `json:"side"`
	OrderType     OrderType          `json:"orderType"`
	ReduceOnly    bool               `json:"reduceOnly"`
	Margin        uint64             `json:"margin"`
	Price         uint64             `json:"price"`
	CreatedAt     int64              `json:"createdAt"`
	ExpiresAt     int64              `json:"expiresAt"`
	ClientOrderId uint64             `json:"clientOrderId"`
	Status        OrderStatus        `json:"status"`
	Bump          uint8              `json:"bump"`
}

func (obj Order) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Id`:
	err = encoder.Encode(obj.Id)
	if err != nil {
		return errors.NewField("Id", err)
	}
	// Serialize `UserMargin`:
	err = encoder.Encode(obj.UserMargin)
	if err != nil {
		return errors.NewField("UserMargin", err)
	}
	// Serialize `User`:
	err = encoder.Encode(obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Serialize `MarketId`:
	err = encoder.Encode(obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Serialize `Side`:
	err = encoder.Encode(obj.Side)
	if err != nil {
		return errors.NewField("Side", err)
	}
	// Serialize `OrderType`:
	err = encoder.Encode(obj.OrderType)
	if err != nil {
		return errors.NewField("OrderType", err)
	}
	// Serialize `ReduceOnly`:
	err = encoder.Encode(obj.ReduceOnly)
	if err != nil {
		return errors.NewField("ReduceOnly", err)
	}
	// Serialize `Margin`:
	err = encoder.Encode(obj.Margin)
	if err != nil {
		return errors.NewField("Margin", err)
	}
	// Serialize `Price`:
	err = encoder.Encode(obj.Price)
	if err != nil {
		return errors.NewField("Price", err)
	}
	// Serialize `CreatedAt`:
	err = encoder.Encode(obj.CreatedAt)
	if err != nil {
		return errors.NewField("CreatedAt", err)
	}
	// Serialize `ExpiresAt`:
	err = encoder.Encode(obj.ExpiresAt)
	if err != nil {
		return errors.NewField("ExpiresAt", err)
	}
	// Serialize `ClientOrderId`:
	err = encoder.Encode(obj.ClientOrderId)
	if err != nil {
		return errors.NewField("ClientOrderId", err)
	}
	// Serialize `Status`:
	err = encoder.Encode(obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj Order) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Order: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Order) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Id`:
	err = decoder.Decode(&obj.Id)
	if err != nil {
		return errors.NewField("Id", err)
	}
	// Deserialize `UserMargin`:
	err = decoder.Decode(&obj.UserMargin)
	if err != nil {
		return errors.NewField("UserMargin", err)
	}
	// Deserialize `User`:
	err = decoder.Decode(&obj.User)
	if err != nil {
		return errors.NewField("User", err)
	}
	// Deserialize `MarketId`:
	err = decoder.Decode(&obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Deserialize `Side`:
	err = decoder.Decode(&obj.Side)
	if err != nil {
		return errors.NewField("Side", err)
	}
	// Deserialize `OrderType`:
	err = decoder.Decode(&obj.OrderType)
	if err != nil {
		return errors.NewField("OrderType", err)
	}
	// Deserialize `ReduceOnly`:
	err = decoder.Decode(&obj.ReduceOnly)
	if err != nil {
		return errors.NewField("ReduceOnly", err)
	}
	// Deserialize `Margin`:
	err = decoder.Decode(&obj.Margin)
	if err != nil {
		return errors.NewField("Margin", err)
	}
	// Deserialize `Price`:
	err = decoder.Decode(&obj.Price)
	if err != nil {
		return errors.NewField("Price", err)
	}
	// Deserialize `CreatedAt`:
	err = decoder.Decode(&obj.CreatedAt)
	if err != nil {
		return errors.NewField("CreatedAt", err)
	}
	// Deserialize `ExpiresAt`:
	err = decoder.Decode(&obj.ExpiresAt)
	if err != nil {
		return errors.NewField("ExpiresAt", err)
	}
	// Deserialize `ClientOrderId`:
	err = decoder.Decode(&obj.ClientOrderId)
	if err != nil {
		return errors.NewField("ClientOrderId", err)
	}
	// Deserialize `Status`:
	err = decoder.Decode(&obj.Status)
	if err != nil {
		return errors.NewField("Status", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *Order) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Order: %w", err)
	}
	return nil
}

func UnmarshalOrder(buf []byte) (*Order, error) {
	obj := new(Order)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type OrderStatus binary.BorshEnum

const (
	OrderStatus_Open OrderStatus = iota
	OrderStatus_Executed
	OrderStatus_Cancelled
	OrderStatus_Expired
)

func (value OrderStatus) String() string {
	switch value {
	case OrderStatus_Open:
		return "Open"
	case OrderStatus_Executed:
		return "Executed"
	case OrderStatus_Cancelled:
		return "Cancelled"
	case OrderStatus_Expired:
		return "Expired"
	default:
		return ""
	}
}

type OrderType binary.BorshEnum

const (
	OrderType_Market OrderType = iota
	OrderType_Limit
)

func (value OrderType) String() string {
	switch value {
	case OrderType_Market:
		return "Market"
	case OrderType_Limit:
		return "Limit"
	default:
		return ""
	}
}

type Pool struct {
	Admin                 solanago.PublicKey `json:"admin"`
	UsdcMint              solanago.PublicKey `json:"usdcMint"`
	OrderEngineProgram    solanago.PublicKey `json:"orderEngineProgram"`
	EngineAuthority       solanago.PublicKey `json:"engineAuthority"`
	LiquidityVault        solanago.PublicKey `json:"liquidityVault"`
	InsuranceVault        solanago.PublicKey `json:"insuranceVault"`
	ProtocolFeeVault      solanago.PublicKey `json:"protocolFeeVault"`
	CooldownSecs          int64              `json:"cooldownSecs"`
	MinLiquidityBufferBps uint16             `json:"minLiquidityBufferBps"`
	LpFeeBps              uint16             `json:"lpFeeBps"`
	InsuranceFeeBps       uint16             `json:"insuranceFeeBps"`
	ProtocolFeeBps        uint16             `json:"protocolFeeBps"`
	ExecutionRebateUsdc   uint64             `json:"executionRebateUsdc"`
	TotalShares           binary.Uint128     `json:"totalShares"`
	PendingKeeperRebates  uint64             `json:"pendingKeeperRebates"`
	TotalTradingFees      uint64             `json:"totalTradingFees"`
	CumulativeTraderPnl   binary.Int128      `json:"cumulativeTraderPnl"`
	Bump                  uint8              `json:"bump"`
}

func (obj Pool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `UsdcMint`:
	err = encoder.Encode(obj.UsdcMint)
	if err != nil {
		return errors.NewField("UsdcMint", err)
	}
	// Serialize `OrderEngineProgram`:
	err = encoder.Encode(obj.OrderEngineProgram)
	if err != nil {
		return errors.NewField("OrderEngineProgram", err)
	}
	// Serialize `EngineAuthority`:
	err = encoder.Encode(obj.EngineAuthority)
	if err != nil {
		return errors.NewField("EngineAuthority", err)
	}
	// Serialize `LiquidityVault`:
	err = encoder.Encode(obj.LiquidityVault)
	if err != nil {
		return errors.NewField("LiquidityVault", err)
	}
	// Serialize `InsuranceVault`:
	err = encoder.Encode(obj.InsuranceVault)
	if err != nil {
		return errors.NewField("InsuranceVault", err)
	}
	// Serialize `ProtocolFeeVault`:
	err = encoder.Encode(obj.ProtocolFeeVault)
	if err != nil {
		return errors.NewField("ProtocolFeeVault", err)
	}
	// Serialize `CooldownSecs`:
	err = encoder.Encode(obj.CooldownSecs)
	if err != nil {
		return errors.NewField("CooldownSecs", err)
	}
	// Serialize `MinLiquidityBufferBps`:
	err = encoder.Encode(obj.MinLiquidityBufferBps)
	if err != nil {
		return errors.NewField("MinLiquidityBufferBps", err)
	}
	// Serialize `LpFeeBps`:
	err = encoder.Encode(obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Serialize `InsuranceFeeBps`:
	err = encoder.Encode(obj.InsuranceFeeBps)
	if err != nil {
		return errors.NewField("InsuranceFeeBps", err)
	}
	// Serialize `ProtocolFeeBps`:
	err = encoder.Encode(obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Serialize `ExecutionRebateUsdc`:
	err = encoder.Encode(obj.ExecutionRebateUsdc)
	if err != nil {
		return errors.NewField("ExecutionRebateUsdc", err)
	}
	// Serialize `TotalShares`:
	err = encoder.Encode(obj.TotalShares)
	if err != nil {
		return errors.NewField("TotalShares", err)
	}
	// Serialize `PendingKeeperRebates`:
	err = encoder.Encode(obj.PendingKeeperRebates)
	if err != nil {
		return errors.NewField("PendingKeeperRebates", err)
	}
	// Serialize `TotalTradingFees`:
	err = encoder.Encode(obj.TotalTradingFees)
	if err != nil {
		return errors.NewField("TotalTradingFees", err)
	}
	// Serialize `CumulativeTraderPnl`:
	err = encoder.Encode(obj.CumulativeTraderPnl)
	if err != nil {
		return errors.NewField("CumulativeTraderPnl", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj Pool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Pool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Pool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `UsdcMint`:
	err = decoder.Decode(&obj.UsdcMint)
	if err != nil {
		return errors.NewField("UsdcMint", err)
	}
	// Deserialize `OrderEngineProgram`:
	err = decoder.Decode(&obj.OrderEngineProgram)
	if err != nil {
		return errors.NewField("OrderEngineProgram", err)
	}
	// Deserialize `EngineAuthority`:
	err = decoder.Decode(&obj.EngineAuthority)
	if err != nil {
		return errors.NewField("EngineAuthority", err)
	}
	// Deserialize `LiquidityVault`:
	err = decoder.Decode(&obj.LiquidityVault)
	if err != nil {
		return errors.NewField("LiquidityVault", err)
	}
	// Deserialize `InsuranceVault`:
	err = decoder.Decode(&obj.InsuranceVault)
	if err != nil {
		return errors.NewField("InsuranceVault", err)
	}
	// Deserialize `ProtocolFeeVault`:
	err = decoder.Decode(&obj.ProtocolFeeVault)
	if err != nil {
		return errors.NewField("ProtocolFeeVault", err)
	}
	// Deserialize `CooldownSecs`:
	err = decoder.Decode(&obj.CooldownSecs)
	if err != nil {
		return errors.NewField("CooldownSecs", err)
	}
	// Deserialize `MinLiquidityBufferBps`:
	err = decoder.Decode(&obj.MinLiquidityBufferBps)
	if err != nil {
		return errors.NewField("MinLiquidityBufferBps", err)
	}
	// Deserialize `LpFeeBps`:
	err = decoder.Decode(&obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Deserialize `InsuranceFeeBps`:
	err = decoder.Decode(&obj.InsuranceFeeBps)
	if err != nil {
		return errors.NewField("InsuranceFeeBps", err)
	}
	// Deserialize `ProtocolFeeBps`:
	err = decoder.Decode(&obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Deserialize `ExecutionRebateUsdc`:
	err = decoder.Decode(&obj.ExecutionRebateUsdc)
	if err != nil {
		return errors.NewField("ExecutionRebateUsdc", err)
	}
	// Deserialize `TotalShares`:
	err = decoder.Decode(&obj.TotalShares)
	if err != nil {
		return errors.NewField("TotalShares", err)
	}
	// Deserialize `PendingKeeperRebates`:
	err = decoder.Decode(&obj.PendingKeeperRebates)
	if err != nil {
		return errors.NewField("PendingKeeperRebates", err)
	}
	// Deserialize `TotalTradingFees`:
	err = decoder.Decode(&obj.TotalTradingFees)
	if err != nil {
		return errors.NewField("TotalTradingFees", err)
	}
	// Deserialize `CumulativeTraderPnl`:
	err = decoder.Decode(&obj.CumulativeTraderPnl)
	if err != nil {
		return errors.NewField("CumulativeTraderPnl", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *Pool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Pool: %w", err)
	}
	return nil
}

func UnmarshalPool(buf []byte) (*Pool, error) {
	obj := new(Pool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PositionLeg binary.BorshEnum

const (
	PositionLeg_Long PositionLeg = iota
	PositionLeg_Short
)

func (value PositionLeg) String() string {
	switch value {
	case PositionLeg_Long:
		return "Long"
	case PositionLeg_Short:
		return "Short"
	default:
		return ""
	}
}

type PricingParams struct {
	BaseSpreadBps         uint16 `json:"baseSpreadBps"`
	SkewCoeffBps          uint16 `json:"skewCoeffBps"`
	MaxFillDeviationBps   uint16 `json:"maxFillDeviationBps"`
	MaxOracleStalenessSec int64  `json:"maxOracleStalenessSec"`
	MaxConfBps            uint16 `json:"maxConfBps"`
}

func (obj PricingParams) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `BaseSpreadBps`:
	err = encoder.Encode(obj.BaseSpreadBps)
	if err != nil {
		return errors.NewField("BaseSpreadBps", err)
	}
	// Serialize `SkewCoeffBps`:
	err = encoder.Encode(obj.SkewCoeffBps)
	if err != nil {
		return errors.NewField("SkewCoeffBps", err)
	}
	// Serialize `MaxFillDeviationBps`:
	err = encoder.Encode(obj.MaxFillDeviationBps)
	if err != nil {
		return errors.NewField("MaxFillDeviationBps", err)
	}
	// Serialize `MaxOracleStalenessSec`:
	err = encoder.Encode(obj.MaxOracleStalenessSec)
	if err != nil {
		return errors.NewField("MaxOracleStalenessSec", err)
	}
	// Serialize `MaxConfBps`:
	err = encoder.Encode(obj.MaxConfBps)
	if err != nil {
		return errors.NewField("MaxConfBps", err)
	}
	return nil
}

func (obj PricingParams) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PricingParams: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PricingParams) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `BaseSpreadBps`:
	err = decoder.Decode(&obj.BaseSpreadBps)
	if err != nil {
		return errors.NewField("BaseSpreadBps", err)
	}
	// Deserialize `SkewCoeffBps`:
	err = decoder.Decode(&obj.SkewCoeffBps)
	if err != nil {
		return errors.NewField("SkewCoeffBps", err)
	}
	// Deserialize `MaxFillDeviationBps`:
	err = decoder.Decode(&obj.MaxFillDeviationBps)
	if err != nil {
		return errors.NewField("MaxFillDeviationBps", err)
	}
	// Deserialize `MaxOracleStalenessSec`:
	err = decoder.Decode(&obj.MaxOracleStalenessSec)
	if err != nil {
		return errors.NewField("MaxOracleStalenessSec", err)
	}
	// Deserialize `MaxConfBps`:
	err = decoder.Decode(&obj.MaxConfBps)
	if err != nil {
		return errors.NewField("MaxConfBps", err)
	}
	return nil
}

func (obj *PricingParams) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PricingParams: %w", err)
	}
	return nil
}

func UnmarshalPricingParams(buf []byte) (*PricingParams, error) {
	obj := new(PricingParams)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type RiskParams struct {
	MaxLeverage      uint16 `json:"maxLeverage"`
	ImrBps           uint16 `json:"imrBps"`
	MmrBps           uint16 `json:"mmrBps"`
	OiCap            uint64 `json:"oiCap"`
	SkewCap          uint64 `json:"skewCap"`
	MaxTradeNotional uint64 `json:"maxTradeNotional"`
}

func (obj RiskParams) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MaxLeverage`:
	err = encoder.Encode(obj.MaxLeverage)
	if err != nil {
		return errors.NewField("MaxLeverage", err)
	}
	// Serialize `ImrBps`:
	err = encoder.Encode(obj.ImrBps)
	if err != nil {
		return errors.NewField("ImrBps", err)
	}
	// Serialize `MmrBps`:
	err = encoder.Encode(obj.MmrBps)
	if err != nil {
		return errors.NewField("MmrBps", err)
	}
	// Serialize `OiCap`:
	err = encoder.Encode(obj.OiCap)
	if err != nil {
		return errors.NewField("OiCap", err)
	}
	// Serialize `SkewCap`:
	err = encoder.Encode(obj.SkewCap)
	if err != nil {
		return errors.NewField("SkewCap", err)
	}
	// Serialize `MaxTradeNotional`:
	err = encoder.Encode(obj.MaxTradeNotional)
	if err != nil {
		return errors.NewField("MaxTradeNotional", err)
	}
	return nil
}

func (obj RiskParams) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding RiskParams: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *RiskParams) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MaxLeverage`:
	err = decoder.Decode(&obj.MaxLeverage)
	if err != nil {
		return errors.NewField("MaxLeverage", err)
	}
	// Deserialize `ImrBps`:
	err = decoder.Decode(&obj.ImrBps)
	if err != nil {
		return errors.NewField("ImrBps", err)
	}
	// Deserialize `MmrBps`:
	err = decoder.Decode(&obj.MmrBps)
	if err != nil {
		return errors.NewField("MmrBps", err)
	}
	// Deserialize `OiCap`:
	err = decoder.Decode(&obj.OiCap)
	if err != nil {
		return errors.NewField("OiCap", err)
	}
	// Deserialize `SkewCap`:
	err = decoder.Decode(&obj.SkewCap)
	if err != nil {
		return errors.NewField("SkewCap", err)
	}
	// Deserialize `MaxTradeNotional`:
	err = decoder.Decode(&obj.MaxTradeNotional)
	if err != nil {
		return errors.NewField("MaxTradeNotional", err)
	}
	return nil
}

func (obj *RiskParams) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling RiskParams: %w", err)
	}
	return nil
}

func UnmarshalRiskParams(buf []byte) (*RiskParams, error) {
	obj := new(RiskParams)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Side binary.BorshEnum

const (
	Side_Buy Side = iota
	Side_Sell
)

func (value Side) String() string {
	switch value {
	case Side_Buy:
		return "Buy"
	case Side_Sell:
		return "Sell"
	default:
		return ""
	}
}

type UserMargin struct {
	Owner             solanago.PublicKey `json:"owner"`
	CollateralBalance uint64             `json:"collateralBalance"`
	NextOrderNonce    uint64             `json:"nextOrderNonce"`
	TotalNotional     uint64             `json:"totalNotional"`
	Bump              uint8              `json:"bump"`
}

func (obj UserMargin) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `CollateralBalance`:
	err = encoder.Encode(obj.CollateralBalance)
	if err != nil {
		return errors.NewField("CollateralBalance", err)
	}
	// Serialize `NextOrderNonce`:
	err = encoder.Encode(obj.NextOrderNonce)
	if err != nil {
		return errors.NewField("NextOrderNonce", err)
	}
	// Serialize `TotalNotional`:
	err = encoder.Encode(obj.TotalNotional)
	if err != nil {
		return errors.NewField("TotalNotional", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj UserMargin) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UserMargin: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UserMargin) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `CollateralBalance`:
	err = decoder.Decode(&obj.CollateralBalance)
	if err != nil {
		return errors.NewField("CollateralBalance", err)
	}
	// Deserialize `NextOrderNonce`:
	err = decoder.Decode(&obj.NextOrderNonce)
	if err != nil {
		return errors.NewField("NextOrderNonce", err)
	}
	// Deserialize `TotalNotional`:
	err = decoder.Decode(&obj.TotalNotional)
	if err != nil {
		return errors.NewField("TotalNotional", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *UserMargin) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UserMargin: %w", err)
	}
	return nil
}

func UnmarshalUserMargin(buf []byte) (*UserMargin, error) {
	obj := new(UserMargin)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UserMarketPosition struct {
	UserMargin            solanago.PublicKey `json:"userMargin"`
	MarketId              uint64             `json:"marketId"`
	LongQty               uint64             `json:"longQty"`
	LongEntryNotional     binary.Uint128     `json:"longEntryNotional"`
	ShortQty              uint64             `json:"shortQty"`
	ShortEntryNotional    binary.Uint128     `json:"shortEntryNotional"`
	LastFundingIndexLong  binary.Int128      `json:"lastFundingIndexLong"`
	LastFundingIndexShort binary.Int128      `json:"lastFundingIndexShort"`
	Bump                  uint8              `json:"bump"`
}

func (obj UserMarketPosition) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `UserMargin`:
	err = encoder.Encode(obj.UserMargin)
	if err != nil {
		return errors.NewField("UserMargin", err)
	}
	// Serialize `MarketId`:
	err = encoder.Encode(obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Serialize `LongQty`:
	err = encoder.Encode(obj.LongQty)
	if err != nil {
		return errors.NewField("LongQty", err)
	}
	// Serialize `LongEntryNotional`:
	err = encoder.Encode(obj.LongEntryNotional)
	if err != nil {
		return errors.NewField("LongEntryNotional", err)
	}
	// Serialize `ShortQty`:
	err = encoder.Encode(obj.ShortQty)
	if err != nil {
		return errors.NewField("ShortQty", err)
	}
	// Serialize `ShortEntryNotional`:
	err = encoder.Encode(obj.ShortEntryNotional)
	if err != nil {
		return errors.NewField("ShortEntryNotional", err)
	}
	// Serialize `LastFundingIndexLong`:
	err = encoder.Encode(obj.LastFundingIndexLong)
	if err != nil {
		return errors.NewField("LastFundingIndexLong", err)
	}
	// Serialize `LastFundingIndexShort`:
	err = encoder.Encode(obj.LastFundingIndexShort)
	if err != nil {
		return errors.NewField("LastFundingIndexShort", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj UserMarketPosition) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UserMarketPosition: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UserMarketPosition) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `UserMargin`:
	err = decoder.Decode(&obj.UserMargin)
	if err != nil {
		return errors.NewField("UserMargin", err)
	}
	// Deserialize `MarketId`:
	err = decoder.Decode(&obj.MarketId)
	if err != nil {
		return errors.NewField("MarketId", err)
	}
	// Deserialize `LongQty`:
	err = decoder.Decode(&obj.LongQty)
	if err != nil {
		return errors.NewField("LongQty", err)
	}
	// Deserialize `LongEntryNotional`:
	err = decoder.Decode(&obj.LongEntryNotional)
	if err != nil {
		return errors.NewField("LongEntryNotional", err)
	}
	// Deserialize `ShortQty`:
	err = decoder.Decode(&obj.ShortQty)
	if err != nil {
		return errors.NewField("ShortQty", err)
	}
	// Deserialize `ShortEntryNotional`:
	err = decoder.Decode(&obj.ShortEntryNotional)
	if err != nil {
		return errors.NewField("ShortEntryNotional", err)
	}
	// Deserialize `LastFundingIndexLong`:
	err = decoder.Decode(&obj.LastFundingIndexLong)
	if err != nil {
		return errors.NewField("LastFundingIndexLong", err)
	}
	// Deserialize `LastFundingIndexShort`:
	err = decoder.Decode(&obj.LastFundingIndexShort)
	if err != nil {
		return errors.NewField("LastFundingIndexShort", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *UserMarketPosition) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UserMarketPosition: %w", err)
	}
	return nil
}

func UnmarshalUserMarketPosition(buf []byte) (*UserMarketPosition, error) {
	obj := new(UserMarketPosition)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
