// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package lp_vault

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_KeeperRebate:
		value := new(KeeperRebate)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as KeeperRebate: %w", err)
		}
		return value, nil
	case Account_LpPosition:
		value := new(LpPosition)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as LpPosition: %w", err)
		}
		return value, nil
	case Account_Pool:
		value := new(Pool)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Pool: %w", err)
		}
		return value, nil
	case Account_WithdrawRequest:
		value := new(WithdrawRequest)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as WithdrawRequest: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_KeeperRebate(accountData []byte) (*KeeperRebate, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_KeeperRebate {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_KeeperRebate, binary.FormatDiscriminator(discriminator))
	}
	acc := new(KeeperRebate)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type KeeperRebate: %w", err)
	}
	return acc, nil
}

func ParseAccount_LpPosition(accountData []byte) (*LpPosition, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_LpPosition {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_LpPosition, binary.FormatDiscriminator(discriminator))
	}
	acc := new(LpPosition)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type LpPosition: %w", err)
	}
	return acc, nil
}

func ParseAccount_Pool(accountData []byte) (*Pool, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Pool {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Pool, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Pool)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Pool: %w", err)
	}
	return acc, nil
}

func ParseAccount_WithdrawRequest(accountData []byte) (*WithdrawRequest, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_WithdrawRequest {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_WithdrawRequest, binary.FormatDiscriminator(discriminator))
	}
	acc := new(WithdrawRequest)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type WithdrawRequest: %w", err)
	}
	return acc, nil
}
