// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package lp_vault

// Account discriminators
var (
	Account_KeeperRebate    = [8]byte{132, 91, 111, 117, 222, 69, 126, 108}
	Account_LpPosition      = [8]byte{105, 241, 37, 200, 224, 2, 252, 90}
	Account_Pool            = [8]byte{241, 154, 109, 4, 17, 177, 109, 188}
	Account_WithdrawRequest = [8]byte{186, 239, 174, 191, 189, 13, 47, 196}
)

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_ApplyLiquidation  = [8]byte{79, 253, 140, 117, 214, 68, 172, 99}
	Instruction_ApplyTradeFill    = [8]byte{121, 167, 72, 65, 72, 145, 84, 71}
	Instruction_ClaimKeeperRebate = [8]byte{79, 11, 116, 46, 28, 152, 224, 61}
	Instruction_ClaimWithdrawLp   = [8]byte{240, 102, 161, 150, 67, 23, 111, 30}
	Instruction_ConfigurePool     = [8]byte{122, 51, 212, 114, 239, 222, 177, 163}
	Instruction_CreateLpPosition  = [8]byte{157, 34, 123, 115, 132, 209, 158, 124}
	Instruction_DepositLp         = [8]byte{83, 107, 16, 26, 26, 20, 130, 56}
	Instruction_InitKeeperRebate  = [8]byte{72, 5, 79, 244, 114, 49, 86, 91}
	Instruction_InitializePool    = [8]byte{95, 180, 10, 172, 84, 174, 232, 40}
	Instruction_RequestWithdrawLp = [8]byte{167, 74, 207, 252, 135, 44, 87, 59}
)
