// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package lp_vault

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "apply_liquidation" instruction.
func NewApplyLiquidationInstruction(
	// Params:
	marketIdParam uint64,
	userParam solanago.PublicKey,
	penaltyParam uint64,
	badDebtParam uint64,

	// Accounts:
	engineAuthorityAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	keeperAccount solanago.PublicKey,
	keeperRebateAccount solanago.PublicKey,
	insuranceVaultAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ApplyLiquidation[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
		// Serialize `userParam`:
		err = enc__.Encode(userParam)
		if err != nil {
			return nil, errors.NewField("userParam", err)
		}
		// Serialize `penaltyParam`:
		err = enc__.Encode(penaltyParam)
		if err != nil {
			return nil, errors.NewField("penaltyParam", err)
		}
		// Serialize `badDebtParam`:
		err = enc__.Encode(badDebtParam)
		if err != nil {
			return nil, errors.NewField("badDebtParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "engine_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 2 "keeper": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperAccount, false, false))
		// Account 3 "keeper_rebate": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperRebateAccount, true, false))
		// Account 4 "insurance_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(insuranceVaultAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "apply_trade_fill" instruction.
func NewApplyTradeFillInstruction(
	// Params:
	marketIdParam uint64,
	userParam solanago.PublicKey,
	orderIdParam uint64,
	notionalParam uint64,
	feeParam uint64,
	pnlDeltaParam int64,

	// Accounts:
	engineAuthorityAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	keeperAccount solanago.PublicKey,
	keeperRebateAccount solanago.PublicKey,
	liquidityVaultAccount solanago.PublicKey,
	insuranceVaultAccount solanago.PublicKey,
	protocolFeeVaultAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ApplyTradeFill[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `marketIdParam`:
		err = enc__.Encode(marketIdParam)
		if err != nil {
			return nil, errors.NewField("marketIdParam", err)
		}
		// Serialize `userParam`:
		err = enc__.Encode(userParam)
		if err != nil {
			return nil, errors.NewField("userParam", err)
		}
		// Serialize `orderIdParam`:
		err = enc__.Encode(orderIdParam)
		if err != nil {
			return nil, errors.NewField("orderIdParam", err)
		}
		// Serialize `notionalParam`:
		err = enc__.Encode(notionalParam)
		if err != nil {
			return nil, errors.NewField("notionalParam", err)
		}
		// Serialize `feeParam`:
		err = enc__.Encode(feeParam)
		if err != nil {
			return nil, errors.NewField("feeParam", err)
		}
		// Serialize `pnlDeltaParam`:
		err = enc__.Encode(pnlDeltaParam)
		if err != nil {
			return nil, errors.NewField("pnlDeltaParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "engine_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 2 "keeper": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperAccount, false, false))
		// Account 3 "keeper_rebate": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperRebateAccount, true, false))
		// Account 4 "liquidity_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(liquidityVaultAccount, false, false))
		// Account 5 "insurance_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(insuranceVaultAccount, false, false))
		// Account 6 "protocol_fee_vault": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeVaultAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "claim_keeper_rebate" instruction.
func NewClaimKeeperRebateInstruction(
	keeperAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	keeperRebateAccount solanago.PublicKey,
	protocolFeeAuthAccount solanago.PublicKey,
	protocolFeeVaultAccount solanago.PublicKey,
	keeperTokenAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "keeper": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperAccount, true, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 2 "keeper_rebate": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperRebateAccount, true, false))
		// Account 3 "protocol_fee_auth": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeAuthAccount, false, false))
		// Account 4 "protocol_fee_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeVaultAccount, true, false))
		// Account 5 "keeper_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperTokenAccountAccount, true, false))
		// Account 6 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "claim_withdraw_lp" instruction.
func NewClaimWithdrawLpInstruction(
	userAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	lpPositionAccount solanago.PublicKey,
	withdrawRequestAccount solanago.PublicKey,
	liquidityAuthAccount solanago.PublicKey,
	liquidityVaultAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 2 "lp_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPositionAccount, true, false))
		// Account 3 "withdraw_request": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(withdrawRequestAccount, true, false))
		// Account 4 "liquidity_auth": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(liquidityAuthAccount, false, false))
		// Account 5 "liquidity_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(liquidityVaultAccount, true, false))
		// Account 6 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 7 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "configure_pool" instruction.
func NewConfigurePoolInstruction(
	// Params:
	paramsParam PoolConfigParams,

	// Accounts:
	adminAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ConfigurePool[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `paramsParam`:
		err = enc__.Encode(paramsParam)
		if err != nil {
			return nil, errors.NewField("paramsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "create_lp_position" instruction.
func NewCreateLpPositionInstruction(
	userAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	lpPositionAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, false, false))
		// Account 2 "lp_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPositionAccount, true, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "deposit_lp" instruction.
func NewDepositLpInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	userAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	lpPositionAccount solanago.PublicKey,
	userTokenAccountAccount solanago.PublicKey,
	liquidityVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_DepositLp[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 2 "lp_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPositionAccount, true, false))
		// Account 3 "user_token_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(userTokenAccountAccount, true, false))
		// Account 4 "liquidity_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(liquidityVaultAccount, true, false))
		// Account 5 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "init_keeper_rebate" instruction.
func NewInitKeeperRebateInstruction(
	keeperAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	keeperRebateAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "keeper": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperAccount, true, true))
		// Account 1 "pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, false, false))
		// Account 2 "keeper_rebate": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(keeperRebateAccount, true, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "initialize_pool" instruction.
func NewInitializePoolInstruction(
	// Params:
	cooldownSecsParam int64,
	minLiquidityBufferBpsParam uint16,

	// Accounts:
	adminAccount solanago.PublicKey,
	usdcMintAccount solanago.PublicKey,
	orderEngineProgramAccount solanago.PublicKey,
	engineAuthorityAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	liquidityAuthAccount solanago.PublicKey,
	insuranceAuthAccount solanago.PublicKey,
	protocolFeeAuthAccount solanago.PublicKey,
	liquidityVaultAccount solanago.PublicKey,
	insuranceVaultAccount solanago.PublicKey,
	protocolFeeVaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_InitializePool[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `cooldownSecsParam`:
		err = enc__.Encode(cooldownSecsParam)
		if err != nil {
			return nil, errors.NewField("cooldownSecsParam", err)
		}
		// Serialize `minLiquidityBufferBpsParam`:
		err = enc__.Encode(minLiquidityBufferBpsParam)
		if err != nil {
			return nil, errors.NewField("minLiquidityBufferBpsParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "admin": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, true, true))
		// Account 1 "usdc_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(usdcMintAccount, false, false))
		// Account 2 "order_engine_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(orderEngineProgramAccount, false, false))
		// Account 3 "engine_authority": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(engineAuthorityAccount, false, false))
		// Account 4 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 5 "liquidity_auth": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(liquidityAuthAccount, false, false))
		// Account 6 "insurance_auth": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(insuranceAuthAccount, false, false))
		// Account 7 "protocol_fee_auth": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeAuthAccount, false, false))
		// Account 8 "liquidity_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(liquidityVaultAccount, true, false))
		// Account 9 "insurance_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(insuranceVaultAccount, true, false))
		// Account 10 "protocol_fee_vault": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(protocolFeeVaultAccount, true, false))
		// Account 11 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 12 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "request_withdraw_lp" instruction.
func NewRequestWithdrawLpInstruction(
	// Params:
	shareAmountParam binary.Uint128,

	// Accounts:
	userAccount solanago.PublicKey,
	poolAccount solanago.PublicKey,
	lpPositionAccount solanago.PublicKey,
	withdrawRequestAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RequestWithdrawLp[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `shareAmountParam`:
		err = enc__.Encode(shareAmountParam)
		if err != nil {
			return nil, errors.NewField("shareAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "user": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(userAccount, true, true))
		// Account 1 "pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(poolAccount, true, false))
		// Account 2 "lp_position": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lpPositionAccount, true, false))
		// Account 3 "withdraw_request": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(withdrawRequestAccount, true, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
