// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package lp_vault

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("7A7BCZChVprUa3WBbC7mER54E7BVGA7PussRB8fHC5tz")
