// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package lp_vault

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type KeeperRebate struct {
	Pool   solanago.PublicKey `json:"pool"`
	Keeper solanago.PublicKey `json:"keeper"`
	Amount uint64             `json:"amount"`
	Bump   uint8              `json:"bump"`
}

func (obj KeeperRebate) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `Keeper`:
	err = encoder.Encode(obj.Keeper)
	if err != nil {
		return errors.NewField("Keeper", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj KeeperRebate) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding KeeperRebate: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *KeeperRebate) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `Keeper`:
	err = decoder.Decode(&obj.Keeper)
	if err != nil {
		return errors.NewField("Keeper", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *KeeperRebate) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling KeeperRebate: %w", err)
	}
	return nil
}

func UnmarshalKeeperRebate(buf []byte) (*KeeperRebate, error) {
	obj := new(KeeperRebate)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type LpPosition struct {
	Owner         solanago.PublicKey `json:"owner"`
	Pool          solanago.PublicKey `json:"pool"`
	Shares        binary.Uint128     `json:"shares"`
	PendingShares binary.Uint128     `json:"pendingShares"`
	WithdrawNonce uint64             `json:"withdrawNonce"`
	Bump          uint8              `json:"bump"`
}

func (obj LpPosition) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `Shares`:
	err = encoder.Encode(obj.Shares)
	if err != nil {
		return errors.NewField("Shares", err)
	}
	// Serialize `PendingShares`:
	err = encoder.Encode(obj.PendingShares)
	if err != nil {
		return errors.NewField("PendingShares", err)
	}
	// Serialize `WithdrawNonce`:
	err = encoder.Encode(obj.WithdrawNonce)
	if err != nil {
		return errors.NewField("WithdrawNonce", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj LpPosition) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LpPosition: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LpPosition) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `Shares`:
	err = decoder.Decode(&obj.Shares)
	if err != nil {
		return errors.NewField("Shares", err)
	}
	// Deserialize `PendingShares`:
	err = decoder.Decode(&obj.PendingShares)
	if err != nil {
		return errors.NewField("PendingShares", err)
	}
	// Deserialize `WithdrawNonce`:
	err = decoder.Decode(&obj.WithdrawNonce)
	if err != nil {
		return errors.NewField("WithdrawNonce", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *LpPosition) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LpPosition: %w", err)
	}
	return nil
}

func UnmarshalLpPosition(buf []byte) (*LpPosition, error) {
	obj := new(LpPosition)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Pool struct {
	Admin                 solanago.PublicKey `json:"admin"`
	UsdcMint              solanago.PublicKey `json:"usdcMint"`
	OrderEngineProgram    solanago.PublicKey `json:"orderEngineProgram"`
	EngineAuthority       solanago.PublicKey `json:"engineAuthority"`
	LiquidityVault        solanago.PublicKey `json:"liquidityVault"`
	InsuranceVault        solanago.PublicKey `json:"insuranceVault"`
	ProtocolFeeVault      solanago.PublicKey `json:"protocolFeeVault"`
	CooldownSecs          int64              `json:"cooldownSecs"`
	MinLiquidityBufferBps uint16             `json:"minLiquidityBufferBps"`
	LpFeeBps              uint16             `json:"lpFeeBps"`
	InsuranceFeeBps       uint16             `json:"insuranceFeeBps"`
	ProtocolFeeBps        uint16             `json:"protocolFeeBps"`
	ExecutionRebateUsdc   uint64             `json:"executionRebateUsdc"`
	TotalShares           binary.Uint128     `json:"totalShares"`
	PendingKeeperRebates  uint64             `json:"pendingKeeperRebates"`
	TotalTradingFees      uint64             `json:"totalTradingFees"`
	CumulativeTraderPnl   binary.Int128      `json:"cumulativeTraderPnl"`
	Bump                  uint8              `json:"bump"`
}

func (obj Pool) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `UsdcMint`:
	err = encoder.Encode(obj.UsdcMint)
	if err != nil {
		return errors.NewField("UsdcMint", err)
	}
	// Serialize `OrderEngineProgram`:
	err = encoder.Encode(obj.OrderEngineProgram)
	if err != nil {
		return errors.NewField("OrderEngineProgram", err)
	}
	// Serialize `EngineAuthority`:
	err = encoder.Encode(obj.EngineAuthority)
	if err != nil {
		return errors.NewField("EngineAuthority", err)
	}
	// Serialize `LiquidityVault`:
	err = encoder.Encode(obj.LiquidityVault)
	if err != nil {
		return errors.NewField("LiquidityVault", err)
	}
	// Serialize `InsuranceVault`:
	err = encoder.Encode(obj.InsuranceVault)
	if err != nil {
		return errors.NewField("InsuranceVault", err)
	}
	// Serialize `ProtocolFeeVault`:
	err = encoder.Encode(obj.ProtocolFeeVault)
	if err != nil {
		return errors.NewField("ProtocolFeeVault", err)
	}
	// Serialize `CooldownSecs`:
	err = encoder.Encode(obj.CooldownSecs)
	if err != nil {
		return errors.NewField("CooldownSecs", err)
	}
	// Serialize `MinLiquidityBufferBps`:
	err = encoder.Encode(obj.MinLiquidityBufferBps)
	if err != nil {
		return errors.NewField("MinLiquidityBufferBps", err)
	}
	// Serialize `LpFeeBps`:
	err = encoder.Encode(obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Serialize `InsuranceFeeBps`:
	err = encoder.Encode(obj.InsuranceFeeBps)
	if err != nil {
		return errors.NewField("InsuranceFeeBps", err)
	}
	// Serialize `ProtocolFeeBps`:
	err = encoder.Encode(obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Serialize `ExecutionRebateUsdc`:
	err = encoder.Encode(obj.ExecutionRebateUsdc)
	if err != nil {
		return errors.NewField("ExecutionRebateUsdc", err)
	}
	// Serialize `TotalShares`:
	err = encoder.Encode(obj.TotalShares)
	if err != nil {
		return errors.NewField("TotalShares", err)
	}
	// Serialize `PendingKeeperRebates`:
	err = encoder.Encode(obj.PendingKeeperRebates)
	if err != nil {
		return errors.NewField("PendingKeeperRebates", err)
	}
	// Serialize `TotalTradingFees`:
	err = encoder.Encode(obj.TotalTradingFees)
	if err != nil {
		return errors.NewField("TotalTradingFees", err)
	}
	// Serialize `CumulativeTraderPnl`:
	err = encoder.Encode(obj.CumulativeTraderPnl)
	if err != nil {
		return errors.NewField("CumulativeTraderPnl", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj Pool) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Pool: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Pool) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `UsdcMint`:
	err = decoder.Decode(&obj.UsdcMint)
	if err != nil {
		return errors.NewField("UsdcMint", err)
	}
	// Deserialize `OrderEngineProgram`:
	err = decoder.Decode(&obj.OrderEngineProgram)
	if err != nil {
		return errors.NewField("OrderEngineProgram", err)
	}
	// Deserialize `EngineAuthority`:
	err = decoder.Decode(&obj.EngineAuthority)
	if err != nil {
		return errors.NewField("EngineAuthority", err)
	}
	// Deserialize `LiquidityVault`:
	err = decoder.Decode(&obj.LiquidityVault)
	if err != nil {
		return errors.NewField("LiquidityVault", err)
	}
	// Deserialize `InsuranceVault`:
	err = decoder.Decode(&obj.InsuranceVault)
	if err != nil {
		return errors.NewField("InsuranceVault", err)
	}
	// Deserialize `ProtocolFeeVault`:
	err = decoder.Decode(&obj.ProtocolFeeVault)
	if err != nil {
		return errors.NewField("ProtocolFeeVault", err)
	}
	// Deserialize `CooldownSecs`:
	err = decoder.Decode(&obj.CooldownSecs)
	if err != nil {
		return errors.NewField("CooldownSecs", err)
	}
	// Deserialize `MinLiquidityBufferBps`:
	err = decoder.Decode(&obj.MinLiquidityBufferBps)
	if err != nil {
		return errors.NewField("MinLiquidityBufferBps", err)
	}
	// Deserialize `LpFeeBps`:
	err = decoder.Decode(&obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Deserialize `InsuranceFeeBps`:
	err = decoder.Decode(&obj.InsuranceFeeBps)
	if err != nil {
		return errors.NewField("InsuranceFeeBps", err)
	}
	// Deserialize `ProtocolFeeBps`:
	err = decoder.Decode(&obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Deserialize `ExecutionRebateUsdc`:
	err = decoder.Decode(&obj.ExecutionRebateUsdc)
	if err != nil {
		return errors.NewField("ExecutionRebateUsdc", err)
	}
	// Deserialize `TotalShares`:
	err = decoder.Decode(&obj.TotalShares)
	if err != nil {
		return errors.NewField("TotalShares", err)
	}
	// Deserialize `PendingKeeperRebates`:
	err = decoder.Decode(&obj.PendingKeeperRebates)
	if err != nil {
		return errors.NewField("PendingKeeperRebates", err)
	}
	// Deserialize `TotalTradingFees`:
	err = decoder.Decode(&obj.TotalTradingFees)
	if err != nil {
		return errors.NewField("TotalTradingFees", err)
	}
	// Deserialize `CumulativeTraderPnl`:
	err = decoder.Decode(&obj.CumulativeTraderPnl)
	if err != nil {
		return errors.NewField("CumulativeTraderPnl", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *Pool) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Pool: %w", err)
	}
	return nil
}

func UnmarshalPool(buf []byte) (*Pool, error) {
	obj := new(Pool)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type PoolConfigParams struct {
	CooldownSecs          int64  `json:"cooldownSecs"`
	MinLiquidityBufferBps uint16 `json:"minLiquidityBufferBps"`
	LpFeeBps              uint16 `json:"lpFeeBps"`
	InsuranceFeeBps       uint16 `json:"insuranceFeeBps"`
	ProtocolFeeBps        uint16 `json:"protocolFeeBps"`
	ExecutionRebateUsdc   uint64 `json:"executionRebateUsdc"`
}

func (obj PoolConfigParams) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `CooldownSecs`:
	err = encoder.Encode(obj.CooldownSecs)
	if err != nil {
		return errors.NewField("CooldownSecs", err)
	}
	// Serialize `MinLiquidityBufferBps`:
	err = encoder.Encode(obj.MinLiquidityBufferBps)
	if err != nil {
		return errors.NewField("MinLiquidityBufferBps", err)
	}
	// Serialize `LpFeeBps`:
	err = encoder.Encode(obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Serialize `InsuranceFeeBps`:
	err = encoder.Encode(obj.InsuranceFeeBps)
	if err != nil {
		return errors.NewField("InsuranceFeeBps", err)
	}
	// Serialize `ProtocolFeeBps`:
	err = encoder.Encode(obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Serialize `ExecutionRebateUsdc`:
	err = encoder.Encode(obj.ExecutionRebateUsdc)
	if err != nil {
		return errors.NewField("ExecutionRebateUsdc", err)
	}
	return nil
}

func (obj PoolConfigParams) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding PoolConfigParams: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *PoolConfigParams) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `CooldownSecs`:
	err = decoder.Decode(&obj.CooldownSecs)
	if err != nil {
		return errors.NewField("CooldownSecs", err)
	}
	// Deserialize `MinLiquidityBufferBps`:
	err = decoder.Decode(&obj.MinLiquidityBufferBps)
	if err != nil {
		return errors.NewField("MinLiquidityBufferBps", err)
	}
	// Deserialize `LpFeeBps`:
	err = decoder.Decode(&obj.LpFeeBps)
	if err != nil {
		return errors.NewField("LpFeeBps", err)
	}
	// Deserialize `InsuranceFeeBps`:
	err = decoder.Decode(&obj.InsuranceFeeBps)
	if err != nil {
		return errors.NewField("InsuranceFeeBps", err)
	}
	// Deserialize `ProtocolFeeBps`:
	err = decoder.Decode(&obj.ProtocolFeeBps)
	if err != nil {
		return errors.NewField("ProtocolFeeBps", err)
	}
	// Deserialize `ExecutionRebateUsdc`:
	err = decoder.Decode(&obj.ExecutionRebateUsdc)
	if err != nil {
		return errors.NewField("ExecutionRebateUsdc", err)
	}
	return nil
}

func (obj *PoolConfigParams) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling PoolConfigParams: %w", err)
	}
	return nil
}

func UnmarshalPoolConfigParams(buf []byte) (*PoolConfigParams, error) {
	obj := new(PoolConfigParams)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type WithdrawRequest struct {
	Owner       solanago.PublicKey `json:"owner"`
	Pool        solanago.PublicKey `json:"pool"`
	Nonce       uint64             `json:"nonce"`
	ShareAmount binary.Uint128     `json:"shareAmount"`
	RequestedAt int64              `json:"requestedAt"`
	Claimed     bool               `json:"claimed"`
	Bump        uint8              `json:"bump"`
}

func (obj WithdrawRequest) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Owner`:
	err = encoder.Encode(obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Serialize `Pool`:
	err = encoder.Encode(obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Serialize `Nonce`:
	err = encoder.Encode(obj.Nonce)
	if err != nil {
		return errors.NewField("Nonce", err)
	}
	// Serialize `ShareAmount`:
	err = encoder.Encode(obj.ShareAmount)
	if err != nil {
		return errors.NewField("ShareAmount", err)
	}
	// Serialize `RequestedAt`:
	err = encoder.Encode(obj.RequestedAt)
	if err != nil {
		return errors.NewField("RequestedAt", err)
	}
	// Serialize `Claimed`:
	err = encoder.Encode(obj.Claimed)
	if err != nil {
		return errors.NewField("Claimed", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj WithdrawRequest) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding WithdrawRequest: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *WithdrawRequest) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Owner`:
	err = decoder.Decode(&obj.Owner)
	if err != nil {
		return errors.NewField("Owner", err)
	}
	// Deserialize `Pool`:
	err = decoder.Decode(&obj.Pool)
	if err != nil {
		return errors.NewField("Pool", err)
	}
	// Deserialize `Nonce`:
	err = decoder.Decode(&obj.Nonce)
	if err != nil {
		return errors.NewField("Nonce", err)
	}
	// Deserialize `ShareAmount`:
	err = decoder.Decode(&obj.ShareAmount)
	if err != nil {
		return errors.NewField("ShareAmount", err)
	}
	// Deserialize `RequestedAt`:
	err = decoder.Decode(&obj.RequestedAt)
	if err != nil {
		return errors.NewField("RequestedAt", err)
	}
	// Deserialize `Claimed`:
	err = decoder.Decode(&obj.Claimed)
	if err != nil {
		return errors.NewField("Claimed", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *WithdrawRequest) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling WithdrawRequest: %w", err)
	}
	return nil
}

func UnmarshalWithdrawRequest(buf []byte) (*WithdrawRequest, error) {
	obj := new(WithdrawRequest)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
